/*
 * SPDX-FileCopyrightText: dgraph2 contributors
 * SPDX-License-Identifier: Apache-2.0
 *
 * gRPC api.DgraphServer adapter. Existing dgo clients connect over gRPC and
 * call Query/Mutate/Alter/CommitOrAbort; we delegate each RPC to *dgraph2.DB.
 *
 * Cluster-only RPCs (Login, CreateNamespace, DropNamespace, ListNamespaces,
 * StreamExtSnapshot, UpdateExtSnapshotStreamingState) are inherited as the
 * UnimplementedDgraphServer no-ops, which return Unimplemented. dgo clients
 * that don't call them work transparently.
 */

package main

import (
	"context"

	"github.com/dgraph-io/dgo/v250/protos/api"

	"github.com/qiangli/dgraph2/pkg/dgraph2"
)

type grpcAdapter struct {
	api.UnimplementedDgraphServer
	db *dgraph2.DB
}

func newGRPCAdapter(db *dgraph2.DB) *grpcAdapter { return &grpcAdapter{db: db} }

// Query implements the DQL query path. The dgo client uses this for both
// queries and mutations bundled in api.Request.
func (g *grpcAdapter) Query(ctx context.Context, req *api.Request) (*api.Response, error) {
	if req == nil {
		return &api.Response{}, nil
	}
	if len(req.Mutations) == 0 {
		return g.db.QueryWithVars(ctx, req.Query, req.Vars)
	}
	// Mixed query + mutations: run mutations first, then the query. We
	// merge each mutation's UID assignments into the final response so dgo
	// callers can resolve their blank-node aliases.
	merged := &api.Response{Uids: map[string]string{}}
	for _, m := range req.Mutations {
		mr, err := g.db.Mutate(ctx, m)
		if err != nil {
			return nil, err
		}
		for k, v := range mr.Uids {
			merged.Uids[k] = v
		}
		if merged.Txn == nil {
			merged.Txn = mr.Txn
		}
	}
	if req.Query == "" {
		return merged, nil
	}
	q, err := g.db.QueryWithVars(ctx, req.Query, req.Vars)
	if err != nil {
		return nil, err
	}
	q.Uids = merged.Uids
	if q.Txn == nil {
		q.Txn = merged.Txn
	}
	return q, nil
}

// Mutate is exposed for dgo clients that hit it directly (older dgo
// versions). Newer ones bundle mutations inside api.Request.
//
// Not strictly required by api.DgraphServer (the autogenerated interface
// only requires Query), but useful as a convenience.
func (g *grpcAdapter) Mutate(ctx context.Context, m *api.Mutation) (*api.Response, error) {
	return g.db.Mutate(ctx, m)
}

// Alter applies a schema change.
func (g *grpcAdapter) Alter(ctx context.Context, op *api.Operation) (*api.Payload, error) {
	if op == nil {
		return &api.Payload{}, nil
	}
	switch {
	case op.DropAll:
		if err := g.db.DropAll(ctx); err != nil {
			return nil, err
		}
		return &api.Payload{}, nil
	case op.DropOp == api.Operation_DATA:
		if err := g.db.DropData(ctx); err != nil {
			return nil, err
		}
		return &api.Payload{}, nil
	case op.DropOp == api.Operation_ATTR:
		if err := g.db.DropPredicate(ctx, op.DropValue); err != nil {
			return nil, err
		}
		return &api.Payload{}, nil
	case op.DropOp == api.Operation_TYPE:
		if err := g.db.DropType(ctx, op.DropValue); err != nil {
			return nil, err
		}
		return &api.Payload{}, nil
	}
	if op.Schema != "" {
		if err := g.db.Alter(ctx, op.Schema); err != nil {
			return nil, err
		}
	}
	return &api.Payload{}, nil
}

// CommitOrAbort is a no-op in dgraph2 because Mutate commits synchronously.
// We acknowledge so dgo's `txn.Commit()` doesn't error out.
func (g *grpcAdapter) CommitOrAbort(_ context.Context, tc *api.TxnContext) (*api.TxnContext, error) {
	if tc == nil {
		return &api.TxnContext{}, nil
	}
	return tc, nil
}

// CheckVersion returns the dgraph2 version string. The package-level `version`
// var in main.go is set at build time via `-ldflags "-X main.version=..."`.
func (g *grpcAdapter) CheckVersion(_ context.Context, _ *api.Check) (*api.Version, error) {
	return &api.Version{Tag: "dgraph2-" + version}, nil
}

// RunDQL is the newer combined-DQL endpoint. Same shape as Query.
func (g *grpcAdapter) RunDQL(ctx context.Context, req *api.RunDQLRequest) (*api.Response, error) {
	if req == nil {
		return &api.Response{}, nil
	}
	return g.db.QueryWithVars(ctx, req.DqlQuery, nil)
}

// AllocateIDs hands out a UID range. dgo uses this for client-side blank-node
// resolution.
func (g *grpcAdapter) AllocateIDs(ctx context.Context, req *api.AllocateIDsRequest) (*api.AllocateIDsResponse, error) {
	if req == nil || req.HowMany == 0 {
		return &api.AllocateIDsResponse{}, nil
	}
	start, end, err := g.db.AssignUid(ctx, req.HowMany)
	if err != nil {
		return nil, err
	}
	return &api.AllocateIDsResponse{Start: start, End: end}, nil
}

type notImplementedError struct{ msg string }

func (e *notImplementedError) Error() string { return e.msg }

func errNotImplementedf(msg string) error { return &notImplementedError{msg: msg} }
